export enum EventKey {
    Escape = 'Escape',
    Enter = 'Enter',
    ArrowUp = 'ArrowUp',
    ArrowDown = 'ArrowDown',
    ArrowLeft = 'ArrowLeft',
    ArrowRight = 'ArrowRight',
}
export enum EventCode {
    KeyBackquote = 'Backquote',
    Key1 = 'Key1',
    Key2 = 'Key2',
    Key3 = 'Key3',
    Key4 = 'Key4',
    Key5 = 'Key5',
    Key6 = 'Key6',
    Key7 = 'Key7',
    Key8 = 'Key8',
    Key9 = 'Key9',
    Key0 = 'Key0',
    KeyMinus = 'Minus',
    KeyEqual = 'Equal',

    KeyA = 'KeyA',
    KeyB = 'KeyB',
    KeyC = 'KeyC',
    KeyD = 'KeyD',
    KeyE = 'KeyE',
    KeyF = 'KeyF',
    KeyG = 'KeyG',
    KeyH = 'KeyH',
    KeyI = 'KeyI',
    KeyJ = 'KeyJ',
    KeyK = 'KeyK',
    KeyL = 'KeyL',
    KeyM = 'KeyM',
    KeyN = 'KeyN',
    KeyO = 'KeyO',
    KeyP = 'KeyP',
    KeyQ = 'KeyQ',
    KeyR = 'KeyR',
    KeyS = 'KeyS',
    KeyT = 'KeyT',
    KeyU = 'KeyU',
    KeyV = 'KeyV',
    KeyW = 'KeyW',
    KeyX = 'KeyX',
    KeyY = 'KeyY',
    KeyZ = 'KeyZ',
    KeyBracketLeft = 'BracketLeft',
    KeyBacketRight = 'BracketRight',
    KeyBackslash = 'Backslash',
    KeyComma = 'Comma',
    KeyPeriod = 'Period',
    KeySlash = 'Slash',
    KeySemicolon = 'Semicolon',
    KeyQuote = 'Quote',
};
/**
 * 可编辑的快捷键集合
 */
export const CanEditorKeys: Set<string> = new Set([
    EventCode.KeyBackquote, EventCode.Key1, EventCode.Key2, EventCode.Key3, EventCode.Key4, EventCode.Key5, EventCode.Key6, EventCode.Key7, EventCode.Key8, EventCode.Key9, EventCode.Key0, EventCode.KeyMinus, EventCode.KeyEqual,
    EventCode.KeyA, EventCode.KeyB, EventCode.KeyC, EventCode.KeyD, EventCode.KeyE, EventCode.KeyF, EventCode.KeyG, EventCode.KeyH, EventCode.KeyI, EventCode.KeyJ, EventCode.KeyK, EventCode.KeyL, EventCode.KeyM, EventCode.KeyN, EventCode.KeyO, EventCode.KeyP, EventCode.KeyQ, EventCode.KeyR, EventCode.KeyS, EventCode.KeyT, EventCode.KeyU, EventCode.KeyV, EventCode.KeyW, EventCode.KeyX, EventCode.KeyY, EventCode.KeyZ,
    EventCode.KeyBracketLeft, EventCode.KeyBacketRight, EventCode.KeyBackslash, EventCode.KeyComma, EventCode.KeyPeriod, EventCode.KeySlash, EventCode.KeySemicolon, EventCode.KeyQuote,
]);